[build]
  command = """
  curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz | tar xf -
  export PATH="$PATH:$PWD/flutter/bin"
  flutter build web
  """
  publish = "build/web"
